LoveSoongAlarm/love-soong-alarm-Backend

- .gitignore
- build.gradle
- src/main/java/com/lovesoongalarm/lovesoongalarm/common/BaseResponse.java
- src/main/java/com/lovesoongalarm/lovesoongalarm/common/code/ErrorCode.java
- src/main/java/com/lovesoongalarm/lovesoongalarm/common/code/GlobalErrorCode.java
- src/main/java/com/lovesoongalarm/lovesoongalarm/common/exception/CustomException.java
- src/main/java/com/lovesoongalarm/lovesoongalarm/common/exception/handler/GlobalExceptionHandler.java
- src/main/java/com/lovesoongalarm/lovesoongalarm/domain/user/persistence/entity/User.java
- src/main/java/com/lovesoongalarm/lovesoongalarm/domain/user/persistence/entity/type/EGender.java
- src/main/java/com/lovesoongalarm/lovesoongalarm/domain/user/persistence/repository/UserRepository.java
- src/main/java/com/lovesoongalarm/lovesoongalarm/domain/user/sub/interest/persistence/entity/Interest.java
- src/main/java/com/lovesoongalarm/lovesoongalarm/domain/user/sub/interest/persistence/repository/InterestRepository.java
- src/main/java/com/lovesoongalarm/lovesoongalarm/domain/user/sub/interest/persistence/type/ELabel.java
- src/main/java/com/lovesoongalarm/lovesoongalarm/domain/user/sub/interest/sub/hashtag/persistence/entity/Hashtag.java
- src/main/java/com/lovesoongalarm/lovesoongalarm/domain/user/sub/interest/sub/hashtag/persistence/repository/HashtagRepository.java
- src/main/resources/application.properties
> Feat/#1 초기세팅

- .github/workflows/deploy.yml
> fix : 배포 workflow 파일 수정

- .github/workflows/deploy.yml
> fix : 배포 workflow 파일 Secrets 값을 미리 환경변수화하도록 수정

- .github/workflows/deploy.yml
- build.gradle
- docker-compose.yml
- src/main/java/com/lovesoongalarm/lovesoongalarm/common/config/RedisConfig.java
- src/main/resources/application-prod.yml
> #9 redis세팅

- build.gradle
- src/main/java/com/lovesoongalarm/lovesoongalarm/common/config/SwaggerConfig.java
> [feat] #14 스웨거 환경설정 구현

- src/main/java/com/lovesoongalarm/lovesoongalarm/domain/location/application/dto/MatchingResultDTO.java
- src/main/java/com/lovesoongalarm/lovesoongalarm/domain/location/application/dto/NearbyUserResponseDTO.java
- src/main/java/com/lovesoongalarm/lovesoongalarm/domain/location/application/facade/LocationFacade.java
- src/main/java/com/lovesoongalarm/lovesoongalarm/domain/location/implement/LocationServiceImpl.java
- src/main/java/com/lovesoongalarm/lovesoongalarm/domain/location/implement/ZoneResolver.java
> [fix] 지도 위치정보 추가

- src/main/java/com/lovesoongalarm/lovesoongalarm/domain/user/application/controller/UserController.java
- src/main/java/com/lovesoongalarm/lovesoongalarm/domain/user/application/dto/UserInterestResponseDTO.java
- src/main/java/com/lovesoongalarm/lovesoongalarm/domain/user/application/dto/UserMeInterestDTO.java
- src/main/java/com/lovesoongalarm/lovesoongalarm/domain/user/application/dto/UserMeResponseDTO.java
- src/main/java/com/lovesoongalarm/lovesoongalarm/domain/user/business/UserQueryService.java
> Feat #73 자신의 프로필 조회 API 구현

- src/main/java/com/lovesoongalarm/lovesoongalarm/domain/location/application/dto/MatchingResultDTO.java
- src/main/java/com/lovesoongalarm/lovesoongalarm/domain/location/application/dto/NearbyUserResponseDTO.java
- src/main/java/com/lovesoongalarm/lovesoongalarm/domain/location/application/facade/LocationFacade.java
- src/main/java/com/lovesoongalarm/lovesoongalarm/domain/location/implement/LocationServiceImpl.java
- src/main/java/com/lovesoongalarm/lovesoongalarm/domain/user/business/UserQueryService.java
> fix : 지도 정보 수정

- src/main/java/com/lovesoongalarm/lovesoongalarm/domain/chat/business/ChatQueryService.java
- src/main/java/com/lovesoongalarm/lovesoongalarm/domain/chat/sub/room/application/converter/ChatRoomConverter.java
- src/main/java/com/lovesoongalarm/lovesoongalarm/domain/chat/sub/room/application/dto/ChatRoomListDTO.java
- src/main/java/com/lovesoongalarm/lovesoongalarm/domain/user/business/UserService.java
> Feat #90 채팅방 목록 조회 시 슬롯 정보도 반환하도록 구현

- src/main/java/com/lovesoongalarm/lovesoongalarm/auth/business/AuthService.java
- src/main/java/com/lovesoongalarm/lovesoongalarm/common/constant/Constants.java
- src/main/java/com/lovesoongalarm/lovesoongalarm/domain/user/business/UserQueryService.java
- src/main/java/com/lovesoongalarm/lovesoongalarm/domain/user/business/UserService.java
- src/main/java/com/lovesoongalarm/lovesoongalarm/domain/user/exception/UserErrorCode.java
- src/main/java/com/lovesoongalarm/lovesoongalarm/domain/user/implement/UserRetriever.java
- src/main/java/com/lovesoongalarm/lovesoongalarm/domain/user/implement/UserValidator.java
- src/main/java/com/lovesoongalarm/lovesoongalarm/domain/user/persistence/entity/User.java
- src/main/java/com/lovesoongalarm/lovesoongalarm/domain/user/persistence/repository/UserRepository.java
> Feat #85 프로필 수정 시 수정 안되는 에러 fix, 회원 탈퇴 시 hard-delete -> soft-delete처리

- src/main/java/com/lovesoongalarm/lovesoongalarm/auth/business/AuthService.java
- src/main/java/com/lovesoongalarm/lovesoongalarm/domain/location/application/dto/NearbyUserResponseDTO.java
- src/main/java/com/lovesoongalarm/lovesoongalarm/domain/location/application/facade/LocationFacade.java
- src/main/java/com/lovesoongalarm/lovesoongalarm/domain/location/implement/SweepUserLocationScheduling.java
- src/main/java/com/lovesoongalarm/lovesoongalarm/domain/user/business/UserService.java
- src/main/java/com/lovesoongalarm/lovesoongalarm/domain/user/exception/UserErrorCode.java
> #115 지도세부기능

- src/main/java/com/lovesoongalarm/lovesoongalarm/domain/notification/application/controller/NotificationController.java
> feat : 알림 swagger 추가

- src/main/java/com/lovesoongalarm/lovesoongalarm/domain/location/application/facade/LocationFacade.java
- src/main/java/com/lovesoongalarm/lovesoongalarm/domain/location/exception/LocationErrorCode.java
- src/main/java/com/lovesoongalarm/lovesoongalarm/domain/location/implement/LocationServiceImpl.java
> fix : location 구역 벗어남 문제 해결

- src/main/java/com/lovesoongalarm/lovesoongalarm/domain/location/application/facade/LocationFacade.java
- src/main/java/com/lovesoongalarm/lovesoongalarm/domain/user/application/dto/UserResponseDTO.java
- src/main/java/com/lovesoongalarm/lovesoongalarm/domain/user/business/UserQueryService.java
- src/main/java/com/lovesoongalarm/lovesoongalarm/domain/user/implement/UserRetriever.java
- src/main/java/com/lovesoongalarm/lovesoongalarm/domain/user/persistence/repository/UserRepository.java
> Feat #129 유저 마지막접속확인

- src/main/java/com/lovesoongalarm/lovesoongalarm/domain/location/implement/LocationServiceImpl.java
> [Hotfix] 지도 구역 벗어난 경우 예외처리

- src/main/java/com/lovesoongalarm/lovesoongalarm/common/util/TimeFormatter.java
- src/main/java/com/lovesoongalarm/lovesoongalarm/domain/location/implement/LocationServiceImpl.java
- src/main/java/com/lovesoongalarm/lovesoongalarm/domain/notification/application/converter/NotificationConverter.java
> [Feature] 알림 전송시간 분기처리

- src/main/java/com/lovesoongalarm/lovesoongalarm/domain/user/business/UserService.java
> [Hotfix] redis 삭제를 pipe에서 분리

- src/main/java/com/lovesoongalarm/lovesoongalarm/domain/chat/business/ChatQueryService.java
- src/main/java/com/lovesoongalarm/lovesoongalarm/domain/chat/sub/room/application/converter/ChatRoomConverter.java
- src/main/java/com/lovesoongalarm/lovesoongalarm/domain/chat/sub/room/application/dto/BlockStatus.java
- src/main/java/com/lovesoongalarm/lovesoongalarm/domain/chat/sub/room/application/dto/ChatRoomDetailDTO.java
- src/main/java/com/lovesoongalarm/lovesoongalarm/domain/chat/sub/room/sub/participant/business/ChatRoomParticipantService.java
- src/main/java/com/lovesoongalarm/lovesoongalarm/domain/pay/exception/PayErrorCode.java
> Feat #168 초기 채팅방 조회 시 내가 차단됐는지 여부 삭제

- src/main/java/com/lovesoongalarm/lovesoongalarm/domain/user/application/converter/UserConverter.java
- src/main/java/com/lovesoongalarm/lovesoongalarm/domain/user/application/dto/UserTicketResponseDTO.java
- src/main/java/com/lovesoongalarm/lovesoongalarm/domain/user/persistence/entity/User.java
> Feat #192 유저 티켓 개수 조회 시 프리패스 여부도 반환하도록 변경

- src/main/java/com/lovesoongalarm/lovesoongalarm/domain/notification/business/NotificationQueryService.java
> [Hotfix] 이미 존재하는지 확인하는 로직 추가

- src/main/java/com/lovesoongalarm/lovesoongalarm/domain/user/application/controller/UserController.java
- src/main/java/com/lovesoongalarm/lovesoongalarm/domain/user/business/UserQueryService.java
> [Hotfix] 나이 음수 시 0 반환

- src/main/java/com/lovesoongalarm/lovesoongalarm/domain/location/application/facade/LocationFacade.java
- src/main/java/com/lovesoongalarm/lovesoongalarm/domain/notification/business/NotificationQueryService.java
> [Refactor] exist로 검증하는 부분 제거
